### ISSUE TITLE
Add a Readme

### ISSUE THREAD

**Issue by JamesMConroy** [schombert/Open-V2#2]
I think the project should have a readme so that people know what the project is. I've made a pull request with a skeleton of a readme file.

**Comment by schombert** [comment]
I do plan on adding a read me file when things get closer to "release," but until then I don't want to be misleading or accidentally overpromise. For example, your suggestion describes the project as a "re-implementation," but that isn't entirely correct. There are some things that are going to be (very) different, and probably some things I am just not going to bother with. My goal is not to make a clone of V2; it's to make something that captures the things I like, or improves on them, and leaves out the things I find tedious or irritating. Because of this inability to say anything concrete, I don't generally intend to point people towards this repository.  I plan on communicating about the project generally via reddit and other public forums, as I don't expect many people to have an interest in the technical side of things. I only posted a link to it because a few people asked, and it felt rude not to.

**Comment by Hannibal-ad-Portas** [comment]
That's a good readme right there. 
Could you at least put up the dependencies so I have a clue about getting it working on my system?

**Comment by schombert** [comment]
The external dependencies are boost, freetype, glew, zlib, and the Windows SDK. A version of Eigen, sqlite, and a modified version of SOIL are included in their entirety. I gave some notes about getting it working in another open issue, but my commits usually reflect what I was doing in a particular day, and so they often don't leave the project in a working state. I will start using the standard github machinery of tagging releases when I have something for general consumption, because when I get to that point there will be well-defined breaks in development simply to create the three binaries with PGO for the three supported instruction sets.

**Comment by asdiamond** [comment]
A lot of people would like to contribute to this, but they are unable to because there isn't a readme, and we don't know how to build this, what we could be working on, etc. Should we get a readme up, with a discord/slack to talk about development?

**Comment by schombert** [comment]
By popular demand, I have added a read me.
